### PR TITLE
Use passive Event (addEventListener options)

### PR DESCRIPTION
**Pull request by petamoriken**

### CODE REVIEW

**Comment by aFarkas** [comment]
I assume you want this as a perf improvement?

I think there is a big misunderstanding when and how to use passive event listeners in the dev community. Passive event listener are introduced to give the browser a hint to improve scroll performance in case the handler does not call `preventDefault`. The main events that profit from this are: `touchmove` and `wheel` and to some degree `touchstart` and `touchend`. 

Despite those named events above, it can be used in conjunction with all `cancelable` events (and maybe in some of those cases browser might improve performance for them also ...). But it doesn't make any sense for event types, that can't be canceled, like `scroll`.

I will accept a PR, where only `cancelable` events (`['click', 'keypress', 'touchstart', 'mousedown']`) use passive listeners.

**Comment by petamoriken** [comment]
I see, I removed waste passive options.

**Comment by aFarkas** [comment]
Thank you, the `scroll` event has still an unneeded passive listener.

**Comment by petamoriken** [comment]
OK, removed it!

**Comment by aFarkas** [comment]
Thanks!

**Pull request merged**
